version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hoboc_frontend
    env_file:
      - src/.env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - network_hoboc_project

networks:
  network_hoboc_project:
    external: true
