version: "3.8"

# ---------------------------------------------------------------------
# Docker Compose Configuration for Hoboc Project
# ---------------------------------------------------------------------
# This setup includes:
#   - PostgreSQL Database
#   - Django Web App (Gunicorn)
#   - Nginx Reverse Proxy
# Volumes are used for persistence.
# Custom network ensures isolated communication between services.

services:
  # -------------------------------------------------------------------
  # PostgreSQL Database Service
  # -------------------------------------------------------------------
  postgres:
    user: "root"                           # Run container processes as root
    container_name: hoboc_database
    image: postgres:15                     # Using official Postgres image
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}         # Database name from .env
      POSTGRES_USER: ${POSTGRES_USER}       # Username from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Password from .env
    volumes:
      - pg_data:/var/lib/postgresql/data    # Persistent storage for DB
    restart: always
    networks:
      - network_hoboc_project

  # -------------------------------------------------------------------
  # Django Web Application Service
  # -------------------------------------------------------------------
  web:
    user: "root"
    container_name: hoboc_web
    image: hoboc_web:${VERSION:-latest}     # Image tag from .env or defaults to 'latest'
    env_file: .env                          # Environment variables for Django app
    volumes:
      - static_volume:/opt/hoboc/src/static/             # Static files volume
      - /var/log/hoboc/backend/django:/var/log/hoboc/backend/django/  # Shared logging directory
      - ./src/:/opt/hoboc/src/                           # Source code mount
    command: gunicorn --config /opt/hoboc/gunicorn.py core.wsgi:application
    restart: always
    networks:
      - network_hoboc_project

  # -------------------------------------------------------------------
  # Nginx Reverse Proxy Service
  # -------------------------------------------------------------------
  nginx:
    user: "root"
    container_name: hoboc_nginx
    build:
      context: ./etc/nginx/                 # Build from custom Nginx config
    volumes:
      - static_volume:/opt/hoboc/static/:ro # Read-only static files for serving
      - ./src/media:/opt/hoboc/src/media:ro # Read-only media files
    depends_on:
      - web                                 # Ensure Django web starts before Nginx
    restart: always
    # WARNING: Remove port mapping when deploying to production
    ports:
      - "80:80"
    networks:
      - network_hoboc_project

# ---------------------------------------------------------------------
# Volumes for Persistent Data
# ---------------------------------------------------------------------
volumes:
  pg_data:          # PostgreSQL data persistence
  static_volume:    # Shared static files between services

# ---------------------------------------------------------------------
# Custom Network
# ---------------------------------------------------------------------
networks:
  network_hoboc_project:
    name: network_hoboc_project
