version: "3.8"

services:
  postgres:
    user: "root"
    container_name: hoboc_database
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - network_hoboc_project

  web:
    user: "root"
    container_name: hoboc_web
    image: hoboc_web:${VERSION:-latest}
    env_file: .env
    volumes:
      - static_volume:/opt/hoboc/src/static/
      - /var/log/hoboc/backend/django:/var/log/hoboc/backend/django/
      - ./src/:/opt/hoboc/src/

    command: gunicorn --config /opt/hoboc/gunicorn.py core.wsgi:application
    restart: always
    networks:
      - network_hoboc_project

  nginx:
    user: "root"
    container_name: hoboc_nginx
    build:
      context: ./etc/nginx/
    volumes:
      - static_volume:/opt/hoboc/static/:ro
    depends_on:
      - web
    restart: always
# this must be remove when you want to deploy(i mean port)
    ports:
      - "80:80"
    networks:
      - network_hoboc_project
volumes:
  pg_data:
  static_volume:

networks:
  network_hoboc_project:
    name: network_hoboc_project
