# Generated by Django 3.2.19 on 2025-06-07 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseslessonmodel',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseslessonmodel',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
