# Generated by Django 3.2.19 on 2025-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0002_auto_20250607_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestopicmodel',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/topics/logos/'),
        ),
        migrations.AlterField(
            model_name='coursestopicmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/topics/images/'),
        ),
    ]
