# Generated by Django 3.2.19 on 2025-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0003_auto_20250609_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestopicmodel',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
