# Generated by Django 3.2.19 on 2025-06-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0004_coursestopicmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestopicmodel',
            name='catchy_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
