# Generated by Django 3.2.19 on 2025-07-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0007_blogpostmodel_blogtagmodel_blogtopicmodel_blogwritermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={'verbose_name': 'Blogs Post ', 'verbose_name_plural': 'Blogs Posts'},
        ),
        migrations.AlterModelOptions(
            name='blogtopicmodel',
            options={'verbose_name': 'Blog Topic', 'verbose_name_plural': 'Blog Topics'},
        ),
    ]
