# Generated by Django 3.2.19 on 2025-07-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0007_blogcategorymodel_blogpostmodel_blogtagmodel_blogwritermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogwritermodel',
            options={'verbose_name': 'Blog Writer', 'verbose_name_plural': 'Blog Writers'},
        ),
    ]
