# Generated by Django 3.2.19 on 2025-07-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0009_notificationsubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together=set(),
        ),
    ]
