# Generated by Django 3.2.19 on 2025-07-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0012_auto_20250725_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('level', models.CharField(choices=[('مبتدی', 'مبتدی'), ('متوسط', 'متوسط'), ('پیشرفته', 'پیشرفته')], default='مبتدی', max_length=20, verbose_name='سطح')),
                ('status', models.CharField(choices=[('شروع\u200cنشده', 'شروع\u200cنشده'), ('در حال یادگیری', 'در حال یادگیری'), ('تکمیل شده', 'تکمیل شده')], default='شروع\u200cنشده', max_length=20, verbose_name='وضعیت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'Roadmap Item',
                'verbose_name_plural': 'Roadmap Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('roadmap_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='hoboc.roadmapitem', verbose_name='آیتم نقشه راه')),
            ],
            options={
                'verbose_name': 'Roadmap Item Source',
                'verbose_name_plural': 'Roadmap Item Sources',
                'ordering': ['order'],
            },
        ),
    ]
