# Generated by Django 3.2.19 on 2025-07-25 09:48

from django.db import migrations, models
import hoboc.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0013_roadmapitem_roadmapresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesubmissionmodel',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=hoboc.models.resume_files_upload_path),
        ),
    ]
