# Generated by Django 3.2.19 on 2025-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0014_alter_resumesubmissionmodel_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='podcasts/episodes/')),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-published_at'],
            },
        ),
    ]
