# Generated by Django 3.2.19 on 2025-09-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0015_podcastepisodemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={'verbose_name': 'Blogs Post', 'verbose_name_plural': 'Blogs Posts'},
        ),
    ]
