# Generated by Django 3.2.19 on 2025-10-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0016_auto_20250901_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('creator', models.CharField(max_length=200, verbose_name='سازنده / نویسنده')),
                ('type', models.CharField(choices=[('book', 'کتاب'), ('website', 'وبسایت'), ('video', 'ویدیو'), ('course', 'دوره'), ('podcast', 'پادکست'), ('article', 'مقاله'), ('company', 'شرکت'), ('friend', 'دوست')], default='book', max_length=20, verbose_name='نوع')),
                ('link', models.URLField(verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['order'],
            },
        ),
    ]
