# Generated by Django 3.2.19 on 2025-10-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoboc', '0017_resourcemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseslessonmodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/lessons/covers/'),
        ),
    ]
